//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleto
    {
        public int ID_Boleto { get; set; }
        public int Folio_Prestamo { get; set; }
        public System.DateTime Primera_Participacion { get; set; }
        public bool Premiado { get; set; }
    
        public virtual prestamo prestamo { get; set; }
    }
}
