//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuenta()
        {
            this.prestamo = new HashSet<prestamo>();
            this.solicitud = new HashSet<solicitud>();
        }
    
        public long Numero_Cuenta { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Persona { get; set; }
        public decimal Saldo { get; set; }
        public string CURP { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual info_persona info_persona { get; set; }
        public virtual curp_estatus curp_estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo> prestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitud> solicitud { get; set; }
    }
}
