//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.prestamo = new HashSet<prestamo>();
        }
    
        public int ID_Empleado { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Persona { get; set; }
        public int Nomina { get; set; }
        public int Prestamos_Aprobados { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual info_persona info_persona { get; set; }
        public virtual nomina nomina1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo> prestamo { get; set; }
    }
}
