//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bancoEntities : DbContext
    {
        public bancoEntities()
            : base("name=bancoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrador> administrador { get; set; }
        public virtual DbSet<boleto> boleto { get; set; }
        public virtual DbSet<cuenta> cuenta { get; set; }
        public virtual DbSet<curp_estatus> curp_estatus { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<gerente> gerente { get; set; }
        public virtual DbSet<info_persona> info_persona { get; set; }
        public virtual DbSet<nomina> nomina { get; set; }
        public virtual DbSet<prestamo> prestamo { get; set; }
        public virtual DbSet<solicitud> solicitud { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
