//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gerente
    {
        public int ID_Gerente { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Persona { get; set; }
        public int Nomina { get; set; }
        public int Dias_Vacaciones { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual info_persona info_persona { get; set; }
        public virtual nomina nomina1 { get; set; }
    }
}
