//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prestamo()
        {
            this.boleto = new HashSet<boleto>();
        }
    
        public int Folio { get; set; }
        public long Numero_Cuenta { get; set; }
        public int ID_Empleado { get; set; }
        public int ID_Solicitud { get; set; }
        public System.DateTime Fecha_Aprobacion { get; set; }
        public string Categoria_Prestamo { get; set; }
        public decimal Pago_Mensual { get; set; }
        public System.DateTime Fecha_Ultimo_Pago { get; set; }
        public decimal Porcentaje_Pagado { get; set; }
        public int Boletos { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boleto> boleto { get; set; }
        public virtual cuenta cuenta { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual solicitud solicitud { get; set; }
    }
}
