//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public solicitud()
        {
            this.prestamo = new HashSet<prestamo>();
        }
    
        public int ID_Solicitud { get; set; }
        public long Numero_Cuenta { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha_Solicitud { get; set; }
        public string Situacion { get; set; }
        public int Plazo { get; set; }
    
        public virtual cuenta cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo> prestamo { get; set; }
    }
}
